# Generated by Django 3.1.1 on 2020-11-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_takemodules'),
        ('students', '0004_auto_20200911_1505'),
    ]

    operations = [
    ]
