<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-09-12 07:09
=======
# Generated by Django 3.1 on 2020-08-30 13:03
>>>>>>> d61ab13ba1f64fc7524107bc5835ffe2f2cafbb9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
<<<<<<< HEAD
                ('staff_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
=======
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=128)),
>>>>>>> d61ab13ba1f64fc7524107bc5835ffe2f2cafbb9
            ],
        ),
    ]
