# Generated by Django 3.1.1 on 2020-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('staff_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
            ],
        ),
    ]
